language: cpp

sudo: required

install:
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls

script:
  - make check
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd Line_Test/tests
  - ./run_tests
  
after_success:
  - cd -
  - cd Line/CMakeFiles/Line.dir
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - coveralls-lcov coverage.info